CC = g++
FLAGS = -std=c++11 -pedantic -Wall -Werror -Wno-sign-compare -Wno-long-long -lm
FILES = dynamic.cpp
PROG = dynamic
dynamic:
	$(CC) $(FLAGS) -o $(PROG) $(FILES)

clean:
	rm -f *.o dynamic